name: 测试

on:
  push:
  workflow_dispatch:

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 安装 Bun
        uses: oven-sh/setup-bun@v1

      - name: 安装依赖
        run: bun install --frozen-lockfile

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: bun docs:build
